nama=("baiq nabila sari")
umur=int(18)
nim=("SI20230007")
semester=("dua")
alamat=("Jorong")
lulusan=("SMK Al-Hasanain")

print("=="*10)
print("selamat datang",nama)
print("umur anda",umur)
print("nim anda",nim)
print("anda semester",semester)
print("alamat anda",alamat)
print("anda lulusan",lulusan)
print("=="*10)
